// Generated by spider on 2025-08-28 21:35:37.284188

class AppIcons {
  AppIcons._();

  static const String menu = 'assets/icons/menu.svg';
  static const String user = 'assets/icons/user.svg';
  static const String warning = 'assets/icons/warning.svg';
}
