targets:
  $default:
    builders:
      # Riverpod 코드 생성
      riverpod_generator:
        generate_for:
          - lib/presentation/providers/**
      
      # AutoRoute 코드 생성
      auto_route_generator:
        generate_for:
          - lib/core/router/**
      
      # Retrofit 코드 생성
      retrofit_generator:
        generate_for:
          - lib/data/datasources/**
      
      # JSON 직렬화 코드 생성
      json_serializable:
        generate_for:
          - lib/data/models/**
          - lib/domain/entities/**
      
      # Freezed 코드 생성
      freezed:
        generate_for:
          - lib/**
