targets:
  $default:
    builders:
      # Riverpod 코드 생성
      riverpod_generator:
        generate_for:
          - lib/**
      
      # AutoRoute 코드 생성
      auto_route_generator:
        generate_for:
          - lib/**
      
      # Retrofit 코드 생성
      retrofit_generator:
        generate_for:
          - lib/data/datasources/**
      
      # JSON 직렬화 코드 생성
      json_serializable:
        generate_for:
          - lib/data/models/**
          - lib/domain/entities/**
      
      # Freezed 코드 생성
      freezed:
        generate_for:
          - lib/**
      
      # Spider 에셋 관리
      spider:
        options:
          # 생성될 클래스 이름
          class_name: "Assets"
          
          # 생성될 파일명 (lib/ 폴더 기준)
          file_name: "core/assets/assets.dart"
          
          # assets 폴더 경로
          assets_path: "assets"
          
          # 패키지명 (pubspec.yaml의 name과 일치해야 함)
          package: "flutter_app"
          
          # SVG 지원 여부
          use_svg: true
          
          # 정렬 여부
          use_sort: true
          
          # 중복 제거 여부
          use_dedup: true
          
          # 생성할 그룹들
          groups:
            - path: "icons"
              class_name: "AppIcons"
              types: [ ".png", ".jpg", ".jpeg", ".svg" ]
            - path: "images"
              class_name: "AppImages"  
              types: [ ".png", ".jpg", ".jpeg", ".webp" ]
            - path: "illustrations"
              class_name: "Illustrations"
              types: [ ".png", ".jpg", ".jpeg", ".svg" ]
            - path: "logos"
              class_name: "Logos"
              types: [ ".png", ".jpg", ".jpeg", ".svg" ]
          
          # 포함할 파일 확장자
          types: [".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp"]
          
          # 제외할 패턴 (translations 폴더 제외)
          ignore: 
            - "translations/**"
          
          # 네이밍 컨벤션
          style: "camelCase"