name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Dependency Injection
  get_it: ^7.7.0

  # Routing
  auto_route: ^7.8.4

  # Localization
  easy_localization: ^3.0.7

  # SVG Support
  flutter_svg: ^2.0.7

  # Local Storage
  shared_preferences: ^2.2.3

  # Network
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Firebase (for future use)
  # firebase_core: ^2.32.0
  # firebase_auth: ^4.20.0
  # cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.12
  riverpod_generator: ^2.3.5
  auto_route_generator: ^7.3.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0
  freezed: ^2.5.2

  # Asset Management
  spider: ^4.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/mock_data/
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/logos/
  
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.ttf
  #       - asset: assets/fonts/Pretendard-Bold.ttf
  #         weight: 700
