// This file will be generated by Spider
// Run: flutter packages pub run build_runner build
// to generate the assets.dart file

export 'asset_helper.dart';
export 'svg_helper.dart';

// The generated Assets class will be available here after running spider
// export 'assets.dart';